### ISSUE TITLE
Starting Tractor After Repairs

### ISSUE THREAD

**Issue by joscmoe** [Frvetz/FS22_RealisticDamageSystem#21]
After I repair damage to a tractor I sometimes cannot start it. Doesn't matter the amount of damage repaired. If I quit the game and go back in the tractor starts normally. I have the autostart turned off.

**Comment by Frvetz** [comment]
Hi,

this is already fixed :) 

just use the latest version if you are playing singleplayer or the second latest version if you are playing multiplayer since there currently is a multiplayer bug. 

Cheers

**Comment by joscmoe** [comment]
Still occurring and I am using the current version 0.9.1.3 and plating single player on Elmcreek. Could it be a conflict with another mod?

**Comment by Frvetz** [comment]
Well in that case... Maybe... 

Do you have any more information about when the problem occurs so I can try to replicate it?

**Comment by Frvetz** [comment]
And could you please send me your log in case the problem occurs again?

You can find it here:
documents -> my games -> Farming Simulator 22 -> log.txt

**Comment by joscmoe** [comment]
It's really random. Doesn't matter the which tractor I'm using. Doesn't seem to matter what time scale but I am usually at 0.5 or 1 when I get the message repairs are completed when I get into the tractor being repaired. Also doesn't seem to matter ho long the session is going. It did happen once today already. Thanks for looking into this!

[log.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14344343/log.txt)

**Comment by Frvetz** [comment]
Very strange... Can't seem to find the cause in the log. Maybe a mod conflict?

**Comment by joscmoe** [comment]
No worries it most likely is a mod not sure which one but it's seems to be better today only one instance where the tractor wouldn't start.

**Comment by Frvetz** [comment]
Sounds good, unfortunately I can't replicate the problem and no else has reported it so far so I would be very happy if you could keep me updated in case you figure out the reason that triggers the problem

Cheers

**Comment by icerkn** [comment]
I ran into this issue last night as well. Map was Castelnaud. Inspected two vehicles, both base game, while they were sitting inside the repair zone for the farm workshop and neither would start once the inspection was done. Inspected two more to test, base game tractor and mod harvester outside the repair zone, and both started fine after the inspection was done.

I run a lot of mods so it's likely a conflict, but I'll see if I can replicate it reliably or pin down what's causing it.

**Comment by Frvetz** [comment]
Alright, thank you!

**Comment by goldenshoes** [comment]
ok, I got same issue with tractor not starting after service is done. Attaching log file
[log.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14470091/log.txt)

**Comment by Wreyth** [comment]
I get the same issue with every repair done won't start until i reload the savegame. and when it does it if you try to re-open the maintenance menu, it just says it cannot perform maintenance already under way. If i then save after repairs are done and reload the save they seem to start fine.

**Comment by Frvetz** [comment]
Could someone please type rdsDebug in the console and send me their log file afterwards (when the issue occurs)? 

Thanks!

**Comment by joscmoe** [comment]
I would do that that but a new issue cropped up so I can't test. My tractors/vehicles are no longer taking any damage. Different vehicles and different maps. Not a bad problem to have lol.

**Comment by joscmoe** [comment]
Ok the game just made a liar out of me lol. My Case Axial-Flow 9250 Harvester now has 1 damage at 92 percent.

**Comment by Frvetz** [comment]
:D my heart dropped already

**Comment by joscmoe** [comment]
However, the percentage did go from 100 to 92 without ticking down a percentage point at a time.

**Comment by pwmeredith** [comment]
Hi there.
Just to let you know that I am having the same issue as Wreyth. I have to exit the save game and go back in and its then ok. Happens on any tractor all the time.

**Comment by Frvetz** [comment]
Please send me a log file after typing "rdsDebug" in the console so I can take a closer look at the calculations of the script (when the issue occurs again) :D thanks

**Comment by Frvetz** [comment]
> However, the percentage did go from 100 to 92 without ticking down a percentage point at a time.

Yeah that's intended 👍 this simulates the occurrence of damages

**Comment by pwmeredith** [comment]
> Please send me a log file after typing "rdsDebug" in the console so I can take a closer look at the calculations of the script (when the issue occurs again) :D thanks

Sorry. I don't understand what you want me to do. I know where the logfile is on my PC. Is this what you require?

**Comment by Frvetz** [comment]
Not exactly. You would need to activate the console in the game file and then enter a command my script provides. 

No problem if you don't know what to do. I'm sure someone else will :)

**Comment by Wreyth** [comment]
> Not exactly. You would need to activate the console in the game file and then enter a command my script provides.
> 
> No problem if you don't know what to do. I'm sure someone else will :)

next time it happens i will try to snag it for you

**Comment by Wreyth** [comment]
log file after rdsDebug

**Comment by Wreyth** [comment]
Went into a loop after repair done and filled the log file to big to upload here but here is the section you most likely needed and a screenshot before running rdsDebug

2024-03-05 16:36 -j3cn47HJBOw+HTgSPGmdoehLorMfFFzriMXh4xWVnL8= :: table: 0x02a1f31c5a08
2024-03-05 16:36 Warning (physics): 2024-03-05 16:36 Static actor moved (Rotoren)
2024-03-05 16:36 Mod version: 0.9.1.4
2024-03-05 16:36 Vehicle name: SUPERCHARGED 6.2L V8
2024-03-05 16:36 Vehicle age: 2
2024-03-05 16:36 Vehicle operating time: 9.9
2024-03-05 16:36 Finish day: 8
2024-03-05 16:36 Current day: 9
2024-03-05 16:36 Finish hour: 20
2024-03-05 16:36 Current hour: 7
2024-03-05 16:36 Finish minute: 18
2024-03-05 16:36 Current minute: 24
2024-03-05 16:36 Number of damages that added base game damage: 0
2024-03-05 16:36 Total number of damages: 0
2024-03-05 16:36 Total number of damages player knows: 0
2024-03-05 16:36 Total number of damages player doesnt know: 0
2024-03-05 16:36 Next operating time for new known damage: 18.39999961853
2024-03-05 16:36 Next operating time for new unknown damage: 32.400001525879
2024-03-05 16:36 Next age for new known damage: 27
2024-03-05 16:36 Next age for new unknown damage: 13
2024-03-05 16:36 Vehicle age when the next inspection is needed: 13
2024-03-05 16:36 General damage multiplier setting: 50
2024-03-05 16:36 Vehicle damage multiplier (should be same as general): 50
2024-03-05 16:36 Players who had tutorial question:
![image](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/4178217/bb935dca-30a9-4864-b9c1-be8bbe6145aa)

**Comment by Frvetz** [comment]
Awesome, thanks a lot!

**Comment by Merrlin** [comment]
Same here... Figured out the CVTRepair Tag in the vehicles.xml is set to true - Even if its a manual shift vehicle

**Comment by Frvetz** [comment]
Ohh then I believe that's the problem. Are you playing multiplayer or singleplayer?

Or has anyone else ever experienced this problem in singleplayer?

**Comment by goldenshoes** [comment]
> Ohh then I believe that's the problem. Are you playing multiplayer or singleplayer?
> 
> Or has anyone else ever experienced this problem in singleplayer?

I had it in SinglePlayer. Didn't play much FS lately to have this issue again

**Comment by Frvetz** [comment]
Alright thank you!! That helps a lot with finding the problem!

**Comment by goldenshoes** [comment]
ok, so just tried making the bug come up again and first tractor started right up with no issues. Then I tried telehandler and no issues what so ever. Both had inspection done first then repairs for 2 damages. Then got electric forklift inspected and reoaired overnight. Slept overnight, then tabbed through all the vehicles after repair was done and it started and drove off right up with no issues. I'm on version 0.9.1.4 in SinglePlayer game and running 1.13.1.1 version of the game. So can we assume that latest FS update fixed it or I just don't remember when there was update for the mod?

**Comment by Frvetz** [comment]
I think it's not fixed yet (at least not from me) and the problem happens more or less randomly. That's what makes it hard to find.

It definitely has to do with the CVT_Addon but that's not his fault and it doesn't matter if the CVT_Addon is active or not. I think my integration has some mistake in it 🤔

**Comment by Merrlin** [comment]
Agree... Maybe I Inspected my Kubota Front loader last night, everything worked fine.

After that I started the normal repair (nothing else). But now it says Maintenance  completed at 18:17 and CVT Repair completed in 1 Day at 18:17.

The corresponding entry in the vehicles.xml says following:

` <RealisticDamageSystem NextInspectionAge="14" DamagesThatAddedWear="6" FinishDay="24" FinishHour="18" FinishMinute="17" DialogSelectedOptionCallback="6" NextKnownDamageAge="42" NextUnknownDamageAge="26" TotalNumberOfDamagesPlayerKnows="6" TotalNumberOfDamagesPlayerDoesntKnow="0" NextKnownDamageOperatingHour="34.900002" NextUnknownDamageOperatingHour="54.900002" DamagesMultiplier="0.250000" FirstLoadNumbersSet="true" MaintenanceActive="true" InspectionActive="false" **CVTRepairActive="false"** EngineDied="true" LengthForDamages=""/>`

Interesting is that the CVTRepairActive is set to false yet the Game Says that CVT Repair is ongoing

**Comment by Frvetz** [comment]
Huh, what the heck. Are you sure you saved the game? Only then the vehicle.xml gets updated

**Comment by Merrlin** [comment]
Yeah of course... Saved the Game shutted down the PC. Today Morning started the Game, found this stange behavior -> Console -> q -> looked into vehicles.xml to figure out what happened

Edit: To add more detail. The Kubota is equiped with hydrostatic drive and had no Gearbox damage and i definitively did not start the Gearbox repair.

Also strange is the EngineDied tag... The Engine did not die.

The whole xml Tag:

`    <vehicle modName="pdlc_kubotaPack" filename="$pdlcdir$kubotaPack/vehicles/kubota/r640/r640.xml" id="21" isAbsolute="true" age="2.000000" price="75500.000000" farmId="1" propertyState="1" operatingTime="21893.994141" selectedObjectIndex="1" subSelectedObjectIndex="1">
        <component index="1" position="263.9482421875 85.224975585938 -667.68341064453" rotation="1.2241377725095 -6.3425619014849 0.0032039112973806"/>
        <component index="2" position="264.08337402344 86.691078186035 -668.89874267578" rotation="1.2253039205886 -6.3423369321291 -0.0068680999715833"/>
        <configuration name="motor" id="1"/>
        <configuration name="wheel" id="VREDESTEIN_DEFAULT"/>
        <configuration name="fillUnit" id="1"/>
        <boughtConfiguration name="wheel" id="TRELLEBORG_DEFAULT"/>
        <boughtConfiguration name="wheel" id="VREDESTEIN_DEFAULT"/>
        <boughtConfiguration name="motor" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <washable>
            <dirtNode amount="1.000000"/>
            <dirtNode amount="1.000000" snowScale="0.000000"/>
            <dirtNode amount="1.000000" snowScale="0.000000"/>
            <dirtNode amount="1.000000" snowScale="0.000000"/>
            <dirtNode amount="1.000000" snowScale="0.000000"/>
        </washable>
        <wearable damage="0.566662">
            <wearNode amount="0.140944"/>
        </wearable>
        <licensePlates variation="1" characters="ULS901___" colorIndex="3" placementIndex="1"/>
        <cylindered>
            <movingTool rotation="-1.817251"/>
            <movingTool rotation="-20.875753"/>
        </cylindered>
        <wheels lastWheelConfiguration="3"/>
        <enterable activeCameraIndex="2" isTabbable="true">
            <camera rotation="-23.199142749793 360 0" translation="0 0 5.3999958174213" zoom="5.400006" fovY="1.037288"/>
            <camera rotation="-52.794499554162 118.68114671715 0" translation="0 2.1431820392609 -1.0446779727936" zoom="2.384246" fovY="1.134464"/>
        </enterable>
        <fillUnit>
            <unit index="1" fillType="DIESEL" fillLevel="37.998058"/>
        </fillUnit>
        <drivable cruiseControl="18" cruiseControlReverse="18"/>
        <aiFieldWorker lastTurnDirection="false"/>
        <attacherJoints comboDirection="-1"/>
        <AutoDrive mode="1" firstMarker="28" secondMarker="1" fillType="1" selectedFillTypes="" loadByFillLevel="true" loopCounter="0" speedLimit="18" fieldSpeedLimit="18" driverName="R640" lastActive="false" AIVElastActive="false" bunkerUnloadType="1" shovelWidth="1" parkInField="2" unloadFillLevel="10" autoTrailerCover="2" useWorkLightsSilo="2" useWorkLightsLoading="2" shovelHeight="26" callSecondUnloader="1" preCallLevel="7" rotateTargets="1" ALUnload="1" useHazardLightReverse="2" maxTriggerDistanceVehicle="0" restrictToField="2" autoRefuel="2" followOnlyOnField="2" followDistance="8" enableParkAtJobFinished="1" autoTipSide="2" pipeOffset="41" useBeaconLights="1" ALUnloadWaitTime="1" exitField="3" cornerSpeed="4" avoidFruit="2" autoRepair="2" activeUnloading="2" groups="2f. Hof Ndby KS,0;3. Wasserstellen,0;9. Feld 21-40,0;2a. Hof Saum,1;1. Verkaufstellen,0;4. Prod Apfelstüble,0;2g. Hof Rehbach,0;9. Felder 141-160,0;3. Apfelwiesen,0;9. Felder 161-173,0;4. Prod Bäckerei,0;2i. Bauunter../ LU,0;2e. Hof Hessen,0;9. Feld 01-20,0;2i. Stallungen,0;3. Feldsilo,0;2d. Frankenhof,0;9. Felder 121-140,0;0. Fahrzeughändler,0;2f. Hof Ndby,0;2c. Hof Schwei.. FS2,0;4. Prod Sägewerk,0;4. Prod Kirchner Mühle,0;2h. BioGasAnlage,0;2c. Hof Schwei.. FS3,0;4. Prod Kalkwerk,0;4. Prod Holzhandel Süd,0;2a. Hof Saum FS 1,0;2h. BioGasSilo 1,0;4. Prod Getreidemühle,0;1. Einkaufstellen,0;3. Waldarbeit,0;2h. BioGasSilo 3,0;9. Feld 81-100,0;9. Feld 61-80,0;9. Feld 41-60,0;2a. Hof Saum FS 2,0;2c. Hof Schweigert,0;3. Point of Interest,0;4. Prod Schreinerei,0;2f. Hof Ndby FS,0;2h. BioGasSilo 2,0;2c. Hof Schwei.. FS1,0;All,0;9. Felder 101-120,0;2b. Hof Oberleitner,0"/>
        <FS22_CVT_Addon>
            <CVTaddon vOne="1" vTwo="4" vThree="2" CVTCanStart="true" vFive="0" autoDiffs="0" CvtConfigId="7" CVTdamage="0.000000"/>
        </FS22_CVT_Addon>
        <FS22_HeadlandManagement>
            <HeadlandManagement configured="false"/>
        </FS22_HeadlandManagement>
        <FS22_WorkCamera>
            <workCamera isEnabled="false">
                <camera fov="80.000000" farClip="500.000000" nearClip="0.010000" flip="false"/>
                <camera fov="60.000000" farClip="100.000000" nearClip="0.010000" flip="false"/>
                <camera fov="70.000000" farClip="200.000000" nearClip="0.010000" flip="false"/>
            </workCamera>
        </FS22_WorkCamera>
        <FS22_park_vehicle>
            <parkVehicle>
                <player id="wUx65mK7Um3UwTrdoMQvtdjqu" isParked="false"/>
            </parkVehicle>
        </FS22_park_vehicle>
        <FS22_AdjustableMirrors>
            <adjustableMirrors version="3.0.0.0">
                <mirror1 position="-0.119 0.023"/>
                <mirror2 position="-0.101 -0.029"/>
            </adjustableMirrors>
        </FS22_AdjustableMirrors>
        <realDirtColor>
            <body r="0.176119" g="0.099202" b="0.025272" curIndex="4.000000" prevIndex="0.100000"/>
            <wheel1 r="0.176043" g="0.099074" b="0.025100" curIndex="4.000000" prevIndex="0.100000"/>
            <wheel2 r="0.176044" g="0.099075" b="0.025100" curIndex="4.000000" prevIndex="0.100000"/>
            <wheel3 r="0.176096" g="0.099163" b="0.025219" curIndex="4.000000" prevIndex="0.100000"/>
            <wheel4 r="0.176043" g="0.099074" b="0.025100" curIndex="4.000000" prevIndex="0.100000"/>
        </realDirtColor>
        <realDirtColorTracks>
            <wheel1 r="0.200000" g="0.140000" b="0.080000" colorIsDefault="true"/>
            <wheel2 r="0.200000" g="0.140000" b="0.080000" colorIsDefault="true"/>
            <wheel3 r="0.200000" g="0.140000" b="0.080000" colorIsDefault="true"/>
            <wheel4 r="0.200000" g="0.140000" b="0.080000" colorIsDefault="true"/>
        </realDirtColorTracks>
        <zzzVehicleControlAddon diffLockAWD="true" brakeForce="1.000000" idleThrottle="false" handbrake="true" diffManual="true" antiSlip="true" snapDistance="1.000000"/>
        <man_FS22_Courseplay>
            <cpVehicleSettings>
                <settings currentValue="1" name="showCourse"/>
                <settings currentValue="true" name="openHudWithMouse"/>
                <settings currentValue="true" name="fuelSave"/>
                <settings currentValue="true" name="turnOnField"/>
                <settings currentValue="true" name="avoidFruit"/>
                <settings currentValue="true" name="allowReversePathfinding"/>
                <settings currentValue="false" name="allowPathfinderTurns"/>
                <settings currentValue="true" name="foldImplementAtEnd"/>
                <settings currentValue="false" name="returnToStart"/>
                <settings currentValue="false" name="raiseImplementLate"/>
                <settings currentValue="false" name="lowerImplementEarly"/>
                <settings currentValue="-1.8790524691781e-14" name="toolOffsetX"/>
                <settings currentValue="1.1" name="baleCollectorOffset"/>
                <settings currentValue="-1.8790524691781e-14" name="combineOffsetX"/>
                <settings currentValue="-1.8790524691781e-14" name="combineOffsetZ"/>
                <settings currentValue="85" name="fullThreshold"/>
                <settings currentValue="false" name="useAdditiveFillUnit"/>
                <settings currentValue="3" name="bunkerSiloWorkWidth"/>
                <settings currentValue="-1.3877787807814e-16" name="loadingShovelHeightOffset"/>
                <settings currentValue="0" name="levelerHeightOffset"/>
                <settings currentValue="false" name="automaticCutterAttach"/>
                <settings currentValue="false" name="stopForUnload"/>
                <settings currentValue="false" name="selfUnload"/>
                <settings currentValue="false" name="unloadOnFirstHeadland"/>
                <settings currentValue="80" name="callUnloaderPercent"/>
                <settings currentValue="2" name="strawSwath"/>
                <settings currentValue="false" name="ridgeMarkersAutomatic"/>
                <settings currentValue="true" name="sowingMachineFertilizerEnabled"/>
                <settings currentValue="false" name="optionalSowingMachineEnabled"/>
                <settings currentValue="false" name="symmetricLaneChange"/>
                <settings currentValue="75" name="convoyDistance"/>
                <settings currentValue="18" name="fieldWorkSpeed"/>
                <settings currentValue="18" name="fieldSpeed"/>
                <settings currentValue="8" name="turnSpeed"/>
                <settings currentValue="5" name="reverseSpeed"/>
                <settings currentValue="15" name="bunkerSiloSpeed"/>
                <settings currentValue="false" name="debugActive"/>
            </cpVehicleSettings>
            <cpCourseGeneratorSettings>
                <settings currentValue="1.6" name="workWidth"/>
                <settings currentValue="1" name="multiTools"/>
                <settings currentValue="0" name="numberOfHeadlands"/>
                <settings currentValue="1" name="startOnHeadland"/>
                <settings currentValue="1" name="headlandCornerType"/>
                <settings currentValue="1" name="isClockwise"/>
                <settings currentValue="7" name="headlandOverlapPercent"/>
                <settings currentValue="1" name="centerMode"/>
                <settings currentValue="5" name="rowDirection"/>
                <settings currentValue="0" name="rowsToSkip"/>
                <settings currentValue="6" name="rowsPerLand"/>
                <settings currentValue="0" name="manualRowAngleDeg"/>
                <settings currentValue="3" name="islandBypassMode"/>
                <settings currentValue="2.1649348980191e-15" name="fieldMargin"/>
                <vineSettings currentValue="0" name="vineCenterOffset"/>
                <vineSettings currentValue="1" name="vineMultiTools"/>
                <vineSettings currentValue="0" name="vineRowsToSkip"/>
            </cpCourseGeneratorSettings>
            <cpAIFieldWorker>
                <cpJob>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="fieldPosition"/>
                    <cpJobParameters currentValue="1" name="startAt"/>
                    <cpJobParameters currentValue="0" name="laneOffset"/>
                </cpJob>
                <cpJobStartAtLastWp>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="fieldPosition"/>
                    <cpJobParameters currentValue="3" name="startAt"/>
                    <cpJobParameters currentValue="0" name="laneOffset"/>
                </cpJobStartAtLastWp>
            </cpAIFieldWorker>
            <cpAIBaleFinder>
                <cpJob>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="fieldPosition"/>
                    <cpJobParameters currentValue="1" name="baleWrapType"/>
                </cpJob>
                <cpJobStartAtLastWp>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="fieldPosition"/>
                    <cpJobParameters currentValue="1" name="baleWrapType"/>
                </cpJobStartAtLastWp>
            </cpAIBaleFinder>
            <cpAICombineUnloader>
                <cpJob>
                    <parameter name="vehicle"/>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="fieldPosition"/>
                    <cpJobParameters currentValue="1" name="unloadTarget"/>
                    <cpJobParameters currentValue="false" name="useGiantsUnload"/>
                    <cpJobParameters currentValue="809" name="unloadingStation"/>
                    <cpJobParameters currentValue="false" name="useFieldUnload"/>
                    <cpJobParameters name="fieldUnloadPosition"/>
                    <cpJobParameters currentValue="-1" name="unloadingTipSide"/>
                </cpJob>
            </cpAICombineUnloader>
            <cpAISiloLoaderWorker>
                <cpJob>
                    <parameter name="vehicle"/>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="loadPosition"/>
                    <cpJobParameters currentValue="1" name="unloadAt"/>
                    <cpJobParameters name="unloadPosition"/>
                    <cpJobParameters currentValue="-1" name="unloadStation"/>
                </cpJob>
            </cpAISiloLoaderWorker>
            <cpAIBunkerSiloWorker>
                <cpJob>
                    <parameter name="vehicle"/>
                    <cpJobParameters name="startPosition"/>
                    <cpJobParameters name="siloPosition"/>
                    <cpJobParameters currentValue="true" name="drivingForwardsIntoSilo"/>
                    <cpJobParameters currentValue="false" name="waitAtParkPosition"/>
                    <cpJobParameters currentValue="false" name="stopWithCompactedSilo"/>
                </cpJob>
            </cpAIBunkerSiloWorker>
        </man_FS22_Courseplay>
        <realisticSeeder currentUnloadMode="1" currentFillUnitNumber="1" isUnloadingToLeft="true"/>
        <RealisticDamageSystem NextInspectionAge="14" DamagesThatAddedWear="6" FinishDay="24" FinishHour="18" FinishMinute="17" DialogSelectedOptionCallback="6" NextKnownDamageAge="42" NextUnknownDamageAge="26" TotalNumberOfDamagesPlayerKnows="6" TotalNumberOfDamagesPlayerDoesntKnow="0" NextKnownDamageOperatingHour="34.900002" NextUnknownDamageOperatingHour="54.900002" DamagesMultiplier="0.250000" FirstLoadNumbersSet="true" MaintenanceActive="true" InspectionActive="false" CVTRepairActive="false" EngineDied="true" LengthForDamages=""/>
    </vehicle>
`

**Comment by Frvetz** [comment]
Okay... Strange... seems like the CVT repair was fully started and finished with removing the damage. Do you know how much money got removed from your account? So if the script thought you hit the CVT button?

And the EngineDied variable is correct. I originally added the variable only for when the engine died but now I also use it when a repair is started (so when the engine should not be useable)

**Comment by Merrlin** [comment]
Now it gets really strange.... After reloading the game, the Message with the Gearbox repair is gone. Only the maintenance til 18:17 is still present (as intended).
Maybe that was caused because the Pallet and the Kubota stands within a Workshoptrigger and I had another vehicle reconfigured recently

The Game didn't remove extra money for the Gearbox repair. only 1881€ for the normal repair.

**Comment by Frvetz** [comment]
That makes sense to me since some people said that a restart fixes the problem that the engine is not starting.

But I have no idea what causes the problem

**Comment by Merrlin** [comment]
It happened again....

Started an Inspection for my Fendt and got an CVT Exchange for 0€...  But no inspection.

Is there a chance to implement something like a debug Logfile? Like wich vehicle was inspected, with woch button was the maintenance started on wich time, how much did it cost etc.? Would make debugging lots easier

**Comment by Frvetz** [comment]
Yeah, already have a console command for that and "Wreyth" already sent me his log file with the debug but it didn't really help me. I know what the problem is but I have no idea why it happens. It just doesn't make any sense that it's happening in singleplayer and not all the time. 

I do have one question though: do you play with the CVT_Addon?

**Comment by Merrlin** [comment]
yeah i use the CVT_Addon.

I didn't mean a console Command. I meant more a separate Logfile (maybe xml in the Savegame Folder) where it shows witch action was performt on witch time... What survives a Reload,  Like

18:18 Inspection Vario 728 100€
19:18 Inspection complete VArio 728
19:34 Maintenance start Vario 728 5 Damages 1234€

**Comment by Frvetz** [comment]
Ahhh okay. That's a good idea! But I think I wouldn't really use it since all the information I need is presented with the debug command and stored in the vehicles.xml from the savegame. Most people explain how the problem occurred when they report it so asking for that file wouldn't bring many new informations 🤷‍♂️ I think it's too much work for the little benefit it has but the idea is good!

**Comment by Merrlin** [comment]
Yeah but you you can compare the actions intended with the actions actually taken.... And you can compare the software output with the vehicles.xml

Like in my, example. I wanted a Inspection but got a Gearbox Exchange after an hour an a Savegame Restart.

But of course thats just my suggestion that such a feature could be helpful

**Comment by Frvetz** [comment]
Yeah you got the gearbox repair because the script thinks a CVT-repair has been started and finishes this repair correctly even if it shouldn't be there.

I know what is happening in the script when the problem occurs but I don't know why. Every mistake the script does has to be a logical mistake from me. Otherwise it would work since the script is just listening to what it's told. But I can't find that logical mistake.

I also don't think the problem occurs randomly. It's some minor action from the player that causes the script to take a different route and end up with a gearbox repair.

I am pretty sure the buttons are not the problem because the CVT-repair is not started 100% correctly. Otherwise you wouldn't have gotten the maintenance + gearbox repair last time and the gearbox repair would stay when reloading the savegame.

But I have no idea why you didn't get the inspection you asked for this time.

**Comment by Wreyth** [comment]
> I think it's not fixed yet (at least not from me) and the problem happens more or less randomly. That's what makes it hard to find.
> 
> It definitely has to do with the CVT_Addon but that's not his fault and it doesn't matter if the CVT_Addon is active or not. I think my integration has some mistake in it 🤔

it happens randomly for me still and i do not have the cvt addon mod installed

**Comment by Frvetz** [comment]
Just published the version 0.9.1.5
The problem might be fixed now but I'm not sure. Could someone who had the problem before try it out? Thank you!

**Comment by pwmeredith** [comment]
> Just published the version 0.9.1.5 The problem might be fixed now but I'm not sure. Could someone who had the problem before try it out? Thank you!

I will be on this afternoon and over the weekend, so I will try it and let you know.
Thanks for your efforts in fixing this. Great mod 👍

**Comment by Frvetz** [comment]
Thank you @pwmeredith! 😃

**Comment by pwmeredith** [comment]
> Just published the version 0.9.1.5 The problem might be fixed now but I'm not sure. Could someone who had the problem before try it out? Thank you!

Ok. I've been in game now and tried it out. The problem is still happening plus a new one has appeared. When I try to exit the game, all the mods disappear in view in front of me, but the game doesn't exit.
Sorry for the bad news. Keep trying please as I love this mod.
I will be happy to test again if you want me too.

**Comment by Merrlin** [comment]
I did a short test yesterday evening and the problem seems to be fixed.
On the first try I got the message that the inspection was done. Before I got the message that the CVT Change was complete.
 
 But now another problem arises. Since some time I get no damage at all… but there I’m unsure if it has something to do with your mod at all. So I need to further investigate.

@pwmeredith i don’t expect anything like this. Can you post your Logfile after FS crashes?

**Comment by Frvetz** [comment]
Alright... Thanks... Yeah log file please and could you tell me how you tested? Since I never get the problem myself. In my tests every repair or inspection works perfectly fine 🤔

And @Merrlin: did you start an inspection? So was the text correct or should it have been the text "repair completed"?
No damage/fault might just be bad luck since it is random since version 0.9.1.4 when a damage/fault occurs. You can look at the variables "NextUnknownDamageAge/OperatingTime" | "NextKnownDamageAge/OperatingTime" with the console command rdsDebug. These variables show the age / operating time of the vehicle when the next damage/fault will occur

**Comment by Merrlin** [comment]
No, everything was fine… I started an inspection and after an hour I got the message inspection complete.

Random faults: Oh there seems to be another bug… I got no damages and no faults for quite a while now ( it seems it started with 0.9.1.4) I also got 100% health for all tractors.
I will check the variables later.

**Comment by Frvetz** [comment]
Hmm okay, thank you!

**Comment by pwmeredith** [comment]
> I did a short test yesterday evening and the problem seems to be fixed. On the first try I got the message that the inspection was done. Before I got the message that the CVT Change was complete.
> 
> But now another problem arises. Since some time I get no damage at all… but there I’m unsure if it has something to do with your mod at all. So I need to further investigate.
> 
> @pwmeredith i don’t expect anything like this. Can you post your Logfile after FS crashes?

Please disregard my comments above. I found a mod that was causing the freezing at exit. Removed this and now carrying out further tests. Will let you know.

**Comment by pwmeredith** [comment]
I think I may of found what's causing the vehicle not to start after repair.
Could somebody put the repair pallet by a vehicle repair icon (spanner) in game so that the zones intersect each other and then do a repair on it using the realistic vehicle repair mod (if that makes sense!). Then when complete, try to start the vehicle please.

**Comment by Merrlin** [comment]
That’s what I’ve done the whole time… 
That was the first thought that crossed my mind. But for now it works even if tractor and Pallet stand in the same Repair Area.

**Comment by Frvetz** [comment]
Ohhh okay. That's super weird since I don't use a area trigger like the game does. The pallet is an object without any triggers so no triggers can interfere. Instead my script searches for the name of the pallet, gets its position and then calculates how far the vehicle is away from the pallet. If it is close enough the button will appear.

But it could be that the vehicle is somehow loaded when it's inside the workshop trigger from the game and then it doesn't start anymore after a repair. It would be awesome if it's fixed now. 

Then the only issue left is the no damages/faults problem

**Comment by Merrlin** [comment]
Yeah as said, it’s not a problem if pallet and tractor are inside the trigger.
I play on Galgenberg and the pallet is inside the lifting platform and the tractor stands right beside in the same room. So no issues here.

maybe the no damage bug is caused because of the reduced maintenance cost mod mentioned in the readme. That was my first thought but didn’t test yet

**Comment by Frvetz** [comment]
Maybe... The reduced maintenance mod no longer serves any function for me, now everything is only controlled by my settings. However, the mod is still supported by my script, as the vehicle would otherwise receive normal FS damage, but that has nothing to do with my damages/faults

**Comment by Frvetz** [comment]
Then I would close this issue for now. As soon as the problem occurs again and someone reports it, I'll reopen the issue 👍 

And @Merrlin - I'll open another issue for the no damages problem so the two problems stay separated 😃

**Comment by goldenshoes** [comment]
Hi! So I use latest version that is 0.9.1.5. Can's start tractor or start repairs now, Uploading log file after rdsDebug command in console

[log.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14963508/log.txt)

**Comment by Frvetz** [comment]
Oh my god. I found the problem. The problem is in the area where I load the saved values from the XML. The variable that is set to true as soon as the engine is not allowed to start (when a maintenance or inspection is started) is loaded for the variable for a CVT maintenance. So this started the CVT maintenance and as a result the variable for the engine start was then set to true again (motor can't start)
